apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    olm.properties: '[{"type": "olm.maxOpenShiftVersion", "value": "4.9"}]'
  name: demo-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: HelloWorld is the Schema for the helloworlds API
      displayName: Hello World
      kind: HelloWorld
      name: helloworlds.demo.example.com
      version: v1alpha1
  description: Demo operator
  displayName: Hello World
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - demo
  links:
  - name: Demo Operator
    url: https://demo-operator.domain
  maturity: alpha
  provider:
    name: slintes
  version: 0.0.0
